package de.marcelhuber.referenzprojektjavase7.view;

/**
 *
 * @author viona05
 */
public class GrundschulVerwaltungGUI01 extends javax.swing.JFrame {

    /**
     * Creates new form GrundschulVerwaltungGUI01
     */
    public GrundschulVerwaltungGUI01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jTabbedPanelGrundschulVerwaltung = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelGrundschullehrer = new javax.swing.JPanel();
        jTextGeburtsname3 = new javax.swing.JTextField();
        jLabelGeburtsname3 = new javax.swing.JLabel();
        jLabelFamilienname3 = new javax.swing.JLabel();
        jTextFamilienname3 = new javax.swing.JTextField();
        jLabelVorname3 = new javax.swing.JLabel();
        jTextVorname3 = new javax.swing.JTextField();
        jLabelZweitname3 = new javax.swing.JLabel();
        jTextZweitname3 = new javax.swing.JTextField();
        jLabelGeburtsdatum3 = new javax.swing.JLabel();
        jFormattedGeburtsdatum3 = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanelGrundschullehrer1 = new javax.swing.JPanel();
        jTextGeburtsname4 = new javax.swing.JTextField();
        jLabelGeburtsname4 = new javax.swing.JLabel();
        jLabelFamilienname4 = new javax.swing.JLabel();
        jTextFamilienname4 = new javax.swing.JTextField();
        jLabelVorname4 = new javax.swing.JLabel();
        jTextVorname4 = new javax.swing.JTextField();
        jLabelZweitname4 = new javax.swing.JLabel();
        jTextZweitname4 = new javax.swing.JTextField();
        jLabelGeburtsdatum4 = new javax.swing.JLabel();
        jFormattedGeburtsdatum4 = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grundschulverwaltungs-Software");

        jDesktopPane2.setName(""); // NOI18N

        jTabbedPanelGrundschulVerwaltung.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jTabbedPanelGrundschulVerwaltung.setName(""); // NOI18N

        jTextGeburtsname3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jTextGeburtsname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGeburtsname3ActionPerformed(evt);
            }
        });

        jLabelGeburtsname3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelGeburtsname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGeburtsname3.setText("Geburtsname");

        jLabelFamilienname3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelFamilienname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFamilienname3.setText("Familienname");

        jTextFamilienname3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jLabelVorname3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelVorname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVorname3.setText("Vorname");

        jTextVorname3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jTextVorname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVorname3ActionPerformed(evt);
            }
        });

        jLabelZweitname3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelZweitname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelZweitname3.setText("Zweitname");

        jTextZweitname3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jLabelGeburtsdatum3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelGeburtsdatum3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGeburtsdatum3.setText("Geburtsdatum");

        jFormattedGeburtsdatum3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFormattedGeburtsdatum3.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jList2.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Fach 01", "Fach 02", "Fach 03" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jCheckBox2.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jCheckBox2.setText("Unterrichtsfächer");

        javax.swing.GroupLayout jPanelGrundschullehrerLayout = new javax.swing.GroupLayout(jPanelGrundschullehrer);
        jPanelGrundschullehrer.setLayout(jPanelGrundschullehrerLayout);
        jPanelGrundschullehrerLayout.setHorizontalGroup(
            jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrundschullehrerLayout.createSequentialGroup()
                .addGroup(jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelGeburtsdatum3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFamilienname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelVorname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelZweitname3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGeburtsname3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelGrundschullehrerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jFormattedGeburtsdatum3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextZweitname3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextVorname3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFamilienname3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextGeburtsname3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanelGrundschullehrerLayout.setVerticalGroup(
            jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrundschullehrerLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeburtsname3)
                    .addComponent(jTextGeburtsname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamilienname3)
                    .addComponent(jTextFamilienname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVorname3)
                    .addComponent(jTextVorname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZweitname3)
                    .addComponent(jTextZweitname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeburtsdatum3)
                    .addComponent(jFormattedGeburtsdatum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrundschullehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGrundschullehrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelGrundschullehrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPanelGrundschulVerwaltung.addTab("Grundschul-Lehrer", jPanel1);

        jTextGeburtsname4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jTextGeburtsname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGeburtsname4ActionPerformed(evt);
            }
        });

        jLabelGeburtsname4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelGeburtsname4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGeburtsname4.setText("Geburtsname");

        jLabelFamilienname4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelFamilienname4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFamilienname4.setText("Familienname");

        jTextFamilienname4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jLabelVorname4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelVorname4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVorname4.setText("Vorname");

        jTextVorname4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jTextVorname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVorname4ActionPerformed(evt);
            }
        });

        jLabelZweitname4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelZweitname4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelZweitname4.setText("Zweitname");

        jTextZweitname4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jLabelGeburtsdatum4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelGeburtsdatum4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGeburtsdatum4.setText("Geburtsdatum");

        jFormattedGeburtsdatum4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFormattedGeburtsdatum4.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanelGrundschullehrer1Layout = new javax.swing.GroupLayout(jPanelGrundschullehrer1);
        jPanelGrundschullehrer1.setLayout(jPanelGrundschullehrer1Layout);
        jPanelGrundschullehrer1Layout.setHorizontalGroup(
            jPanelGrundschullehrer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrundschullehrer1Layout.createSequentialGroup()
                .addGroup(jPanelGrundschullehrer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelGeburtsdatum4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFamilienname4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVorname4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelZweitname4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGeburtsname4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelGrundschullehrer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jFormattedGeburtsdatum4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(jTextZweitname4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextVorname4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFamilienname4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextGeburtsname4, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanelGrundschullehrer1Layout.setVerticalGroup(
            jPanelGrundschullehrer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrundschullehrer1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanelGrundschullehrer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeburtsname4)
                    .addComponent(jTextGeburtsname4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrundschullehrer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamilienname4)
                    .addComponent(jTextFamilienname4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrundschullehrer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVorname4)
                    .addComponent(jTextVorname4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrundschullehrer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZweitname4)
                    .addComponent(jTextZweitname4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrundschullehrer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeburtsdatum4)
                    .addComponent(jFormattedGeburtsdatum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGrundschullehrer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelGrundschullehrer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPanelGrundschulVerwaltung.addTab("Mensch", jPanel2);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelGrundschulVerwaltung)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelGrundschulVerwaltung)
                .addContainerGap())
        );
        jDesktopPane2.setLayer(jTabbedPanelGrundschulVerwaltung, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPanelGrundschulVerwaltung.getAccessibleContext().setAccessibleDescription("");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jDesktopPane2.getAccessibleContext().setAccessibleName("");
        jDesktopPane2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextVorname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVorname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVorname3ActionPerformed

    private void jTextGeburtsname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGeburtsname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGeburtsname3ActionPerformed

    private void jTextGeburtsname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGeburtsname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGeburtsname4ActionPerformed

    private void jTextVorname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVorname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVorname4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrundschulVerwaltungGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrundschulVerwaltungGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrundschulVerwaltungGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrundschulVerwaltungGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrundschulVerwaltungGUI01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JFormattedTextField jFormattedGeburtsdatum3;
    private javax.swing.JFormattedTextField jFormattedGeburtsdatum4;
    private javax.swing.JLabel jLabelFamilienname3;
    private javax.swing.JLabel jLabelFamilienname4;
    private javax.swing.JLabel jLabelGeburtsdatum3;
    private javax.swing.JLabel jLabelGeburtsdatum4;
    private javax.swing.JLabel jLabelGeburtsname3;
    private javax.swing.JLabel jLabelGeburtsname4;
    private javax.swing.JLabel jLabelVorname3;
    private javax.swing.JLabel jLabelVorname4;
    private javax.swing.JLabel jLabelZweitname3;
    private javax.swing.JLabel jLabelZweitname4;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelGrundschullehrer;
    private javax.swing.JPanel jPanelGrundschullehrer1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPanelGrundschulVerwaltung;
    private javax.swing.JTextField jTextFamilienname3;
    private javax.swing.JTextField jTextFamilienname4;
    private javax.swing.JTextField jTextGeburtsname3;
    private javax.swing.JTextField jTextGeburtsname4;
    private javax.swing.JTextField jTextVorname3;
    private javax.swing.JTextField jTextVorname4;
    private javax.swing.JTextField jTextZweitname3;
    private javax.swing.JTextField jTextZweitname4;
    // End of variables declaration//GEN-END:variables
}
