package de.marcelhuber.referenzprojektjavase7.view;

/**
 *
 * @author viona05
 */
public class GrundschulVerwaltungGUI01 extends javax.swing.JFrame {

    /**
     * Creates new form GrundschulVerwaltungGUI01
     */
    public GrundschulVerwaltungGUI01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jTabbedPanelGrundschulVerwaltung = new javax.swing.JTabbedPane();
        jPanelGrundschulLehrer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextGeburtsname1 = new javax.swing.JTextField();
        jLabelGeburtsname1 = new javax.swing.JLabel();
        jLabelFamilienname1 = new javax.swing.JLabel();
        jTextFamilienname1 = new javax.swing.JTextField();
        jLabelVorname1 = new javax.swing.JLabel();
        jTextVorname1 = new javax.swing.JTextField();
        jLabelZweitname1 = new javax.swing.JLabel();
        jTextZweitname1 = new javax.swing.JTextField();
        jLabelGeburtsdatum1 = new javax.swing.JLabel();
        jFormattedGeburtsdatum1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanelGrundschulMensch = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextGeburtsname = new javax.swing.JTextField();
        jLabelGeburtsname = new javax.swing.JLabel();
        jLabelFamilienname = new javax.swing.JLabel();
        jTextFamilienname = new javax.swing.JTextField();
        jLabelVorname = new javax.swing.JLabel();
        jTextVorname = new javax.swing.JTextField();
        jLabelZweitname = new javax.swing.JLabel();
        jTextZweitname = new javax.swing.JTextField();
        jLabelGeburtsdatum = new javax.swing.JLabel();
        jFormattedGeburtsdatum = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grundschulverwaltungs-Software");

        jDesktopPane2.setName(""); // NOI18N

        jTabbedPanelGrundschulVerwaltung.setName(""); // NOI18N

        jTextGeburtsname1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jTextGeburtsname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGeburtsname1ActionPerformed(evt);
            }
        });

        jLabelGeburtsname1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelGeburtsname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGeburtsname1.setText("Geburtsname");

        jLabelFamilienname1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelFamilienname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFamilienname1.setText("Familienname");

        jTextFamilienname1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jLabelVorname1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelVorname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVorname1.setText("Vorname");

        jTextVorname1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jTextVorname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVorname1ActionPerformed(evt);
            }
        });

        jLabelZweitname1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelZweitname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelZweitname1.setText("Zweitname");

        jTextZweitname1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jLabelGeburtsdatum1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelGeburtsdatum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGeburtsdatum1.setText("Geburtsdatum");

        jFormattedGeburtsdatum1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFormattedGeburtsdatum1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jList1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Fach 01", "Fach 02", "Fach 03" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jCheckBox1.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jCheckBox1.setText("Unterrichtsfächer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelGeburtsdatum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelGeburtsname1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabelFamilienname1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabelVorname1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabelZweitname1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextGeburtsname1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                            .addComponent(jTextFamilienname1)
                            .addComponent(jTextVorname1)
                            .addComponent(jTextZweitname1)
                            .addComponent(jFormattedGeburtsdatum1))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeburtsname1)
                    .addComponent(jTextGeburtsname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamilienname1)
                    .addComponent(jTextFamilienname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVorname1)
                    .addComponent(jTextVorname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZweitname1)
                    .addComponent(jTextZweitname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeburtsdatum1)
                    .addComponent(jFormattedGeburtsdatum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGrundschulLehrerLayout = new javax.swing.GroupLayout(jPanelGrundschulLehrer);
        jPanelGrundschulLehrer.setLayout(jPanelGrundschulLehrerLayout);
        jPanelGrundschulLehrerLayout.setHorizontalGroup(
            jPanelGrundschulLehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGrundschulLehrerLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelGrundschulLehrerLayout.setVerticalGroup(
            jPanelGrundschulLehrerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGrundschulLehrerLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPanelGrundschulVerwaltung.addTab("Grundschul-Lehrer", jPanelGrundschulLehrer);

        jTextGeburtsname.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jTextGeburtsname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGeburtsnameActionPerformed(evt);
            }
        });

        jLabelGeburtsname.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelGeburtsname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGeburtsname.setText("Geburtsname");

        jLabelFamilienname.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelFamilienname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFamilienname.setText("Familienname");

        jTextFamilienname.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jLabelVorname.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelVorname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVorname.setText("Vorname");

        jTextVorname.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jTextVorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVornameActionPerformed(evt);
            }
        });

        jLabelZweitname.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelZweitname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelZweitname.setText("Zweitname");

        jTextZweitname.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        jLabelGeburtsdatum.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N
        jLabelGeburtsdatum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGeburtsdatum.setText("Geburtsdatum");

        jFormattedGeburtsdatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFormattedGeburtsdatum.setFont(new java.awt.Font("Vani", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelGeburtsdatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGeburtsname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabelFamilienname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabelVorname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabelZweitname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextGeburtsname, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(jTextFamilienname)
                    .addComponent(jTextVorname)
                    .addComponent(jTextZweitname)
                    .addComponent(jFormattedGeburtsdatum))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeburtsname)
                    .addComponent(jTextGeburtsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFamilienname)
                    .addComponent(jTextFamilienname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVorname)
                    .addComponent(jTextVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZweitname)
                    .addComponent(jTextZweitname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeburtsdatum)
                    .addComponent(jFormattedGeburtsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGrundschulMenschLayout = new javax.swing.GroupLayout(jPanelGrundschulMensch);
        jPanelGrundschulMensch.setLayout(jPanelGrundschulMenschLayout);
        jPanelGrundschulMenschLayout.setHorizontalGroup(
            jPanelGrundschulMenschLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGrundschulMenschLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelGrundschulMenschLayout.setVerticalGroup(
            jPanelGrundschulMenschLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGrundschulMenschLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelGrundschulMensch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelGrundschulMensch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPanelGrundschulVerwaltung.addTab("Mensch", jPanel1);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelGrundschulVerwaltung)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelGrundschulVerwaltung)
                .addContainerGap())
        );
        jDesktopPane2.setLayer(jTabbedPanelGrundschulVerwaltung, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPanelGrundschulVerwaltung.getAccessibleContext().setAccessibleDescription("");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jDesktopPane2.getAccessibleContext().setAccessibleName("");
        jDesktopPane2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextVorname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVorname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVorname1ActionPerformed

    private void jTextGeburtsname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGeburtsname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGeburtsname1ActionPerformed

    private void jTextGeburtsnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGeburtsnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGeburtsnameActionPerformed

    private void jTextVornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVornameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrundschulVerwaltungGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrundschulVerwaltungGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrundschulVerwaltungGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrundschulVerwaltungGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrundschulVerwaltungGUI01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JFormattedTextField jFormattedGeburtsdatum;
    private javax.swing.JFormattedTextField jFormattedGeburtsdatum1;
    private javax.swing.JLabel jLabelFamilienname;
    private javax.swing.JLabel jLabelFamilienname1;
    private javax.swing.JLabel jLabelGeburtsdatum;
    private javax.swing.JLabel jLabelGeburtsdatum1;
    private javax.swing.JLabel jLabelGeburtsname;
    private javax.swing.JLabel jLabelGeburtsname1;
    private javax.swing.JLabel jLabelVorname;
    private javax.swing.JLabel jLabelVorname1;
    private javax.swing.JLabel jLabelZweitname;
    private javax.swing.JLabel jLabelZweitname1;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelGrundschulLehrer;
    private javax.swing.JPanel jPanelGrundschulMensch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPanelGrundschulVerwaltung;
    private javax.swing.JTextField jTextFamilienname;
    private javax.swing.JTextField jTextFamilienname1;
    private javax.swing.JTextField jTextGeburtsname;
    private javax.swing.JTextField jTextGeburtsname1;
    private javax.swing.JTextField jTextVorname;
    private javax.swing.JTextField jTextVorname1;
    private javax.swing.JTextField jTextZweitname;
    private javax.swing.JTextField jTextZweitname1;
    // End of variables declaration//GEN-END:variables
}
